name: Generic CI Workflow

on:
  push:
    branches:
      - '*'       # Matches any branch
      - '*/*'     # matches every branch containing a single '/'
      - '**'      # matches every branch
  pull_request:
    types: [ assigned, opened, synchronize, reopened, closed ]
jobs:
  loopcheck:
    runs-on: [ubuntu-latest]
    steps:
      - name: test
        run: |
          strategy:
            matrix:
              files: [test1, test2]
              echo ${{ matrix.files }}.scss
