name: Generic CI Workflow

on:
  push:
    branches:
      - '*'       # Matches any branch
      - '*/*'     # matches every branch containing a single '/'
      - '**'      # matches every branch
  pull_request:
    types: [ assigned, opened, synchronize, reopened, closed ]
    
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '${{toJson(github.event.pull_request)}}'
          echo ${{github.event.pull_request.number}}
          echo ${{github.event.pull_request.merged}}
          echo ${{github.event.pull_request.state}}
          echo ${{'refs/heads/'github.event.pull_request.head.ref}}          
          
      - name: Create comment
        if: ${{github.event.pull_request.merged && github.event.pull_request.head.ref == 'Release26' }}
        uses: peter-evans/create-or-update-comment@v1
        env:
            GEN_TOKEN: ${{ secrets.APP_KEY }}
        with:
          token: ${{ env.GEN_TOKEN }}
          issue-number: ${{github.event.pull_request.number}}
          body: |
            /deploy version=99999999 env=preprod
          reactions: '+2'
