name: Dispatch Workflow

on:
  issue_comment:
    types: [created]
    
  #push:
   # branches:
    #  - '*'       # Matches any branch
    #  - '*/*'     # matches every branch containing a single '/'
    #  - '**'      # matches every branch

jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
       - name: Print Event 
         env:
            eventObj: ${{toJson(github.event)}}
         run: | 
           eventObj1=${{evn.eventObj}}
           action=`echo $(jq -r '.action' <<< "$eventObj1")`
           echo $action
           echo "${{ github.event.client_payload.github.issue.number }}"
           
       - name: Slash Command Dispatch
         uses: peter-evans/slash-command-dispatch@v2
         env:
            GEN_TOKEN: ${{ secrets.APP_KEY }}
         with:
           token: ${{ env.GEN_TOKEN }}
           commands: |
             deploy
           repository: NaseerMohammedAbdul/dispatch
